name: "Conformer-CTC-Char"

#define model
model:
  sample_rate: 16000
  labels:  [" ", "a", "b", "c", "d", "e",
            "f", "g", "h", "i", "j", "k",
            "l", "m", "n", "o", "p", "q",
            "r", "s", "t", "u", "v", "w",
            "x", "y", "z", "'"]
  log_prediction: true 
  ctc_reduction: 'mean_batch'
  skip_nan_grad: false

  #specify traing data
  train_ds:
    manifest_filepath: ???
    labels:  [" ", "a", "b", "c", "d", "e",
              "f", "g", "h", "i", "j", "k",
              "l", "m", "n", "o", "p", "q",
              "r", "s", "t", "u", "v", "w",
              "x", "y", "z", "'"]
    sample_rate: 16000
    #adjust these for GPU/CPU limits
    batch_size: 16
    shuffle: true
    num_workers: 4
    pin_memory: true
    trim_silence: false
    max_duration: 16.7
    min_duration: 0.1
    #tarred datasets
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    #bucketing parameters
    bucketing_strategy: "synced_randomized"
    bucketing_batch_size: null

  #specify validation data
  validation_ds:
    manifest_filepath: ???
    labels:  [" ", "a", "b", "c", "d", "e",
              "f", "g", "h", "i", "j", "k",
              "l", "m", "n", "o", "p", "q",
              "r", "s", "t", "u", "v", "w",
              "x", "y", "z", "'"]
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true

  #specify test data
  test_ds:
    manifest_filepath: null
    labels:  [" ", "a", "b", "c", "d", "e",
              "f", "g", "h", "i", "j", "k",
              "l", "m", "n", "o", "p", "q",
              "r", "s", "t", "u", "v", "w",
              "x", "y", "z", "'"]
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true

  #specify input
  preprocessor:
    _target_: "nemo.collections.asr.modules.\
       AudioToMelSpectrogramPreprocessor"
    sample_rate: 16000
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: 80
    n_fft: 512
    log: true
    frame_splicing: 1
    dither: 0.00001
    pad_to: 0
    pad_value: 0.0

  #do augmentation
  spec_augment:
    _target_: "nemo.collections.asr.modules.\
      SpectrogramAugmentation"
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05

  #specify encoder architecture
  encoder:
    _target_: "nemo.collections.asr.modules.\
      ConformerEncoder"
    feat_in: 80
    feat_out: -1
    n_layers: 16
    d_model: 256

    #sub-sampling parameters
    subsampling: striding
    subsampling_factor: 4
    subsampling_conv_channels: -1
    causal_downsampling: false

    #feed forward module parameters
    ff_expansion_factor: 4

    #multi-head attention parameters
    self_attention_model: rel_pos
    n_heads: 8
    att_context_size: [-1, -1]
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000

    #convolution module parameters
    conv_kernel_size: 31
    conv_norm_type: 'batch_norm'
    conv_context_size: null

    #regularization
    dropout: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1

  decoder:
    _target_: "nemo.collections.asr.\
      modules.ConvASRDecoder"
    feat_in: null
    num_classes: -1
    vocabulary:  [" ", "a", "b", "c", "d",
                  "e", "f", "g", "h", "i",
                  "j", "k", "l", "m", "n",
                  "o", "p", "q", "r", "s",
                  "t", "u", "v", "w", "x",
                  "y", "z", "'"]

  #Adam optimizer
  optim:
    name: adamw
    lr: 2.0
    # optimizer arguments
    betas: [0.9, 0.98]
    weight_decay: 1e-3

    #scheduler setup
    sched:
      name: NoamAnnealing
      d_model: 256
      warmup_steps: 10000
      warmup_ratio: null
      min_lr: 1e-6

#training parameters
trainer:
  devices: -1
  num_nodes: 1
  max_epochs: 1000
  max_steps: -1
  val_check_interval: 1.0
  accelerator: auto
  strategy: ddp
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  precision: 32
  log_every_n_steps: 10
  enable_progress_bar: True
  resume_from_checkpoint: null
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  sync_batchnorm: true
  enable_checkpointing: False
  logger: false
  benchmark: false

#more training parameters
exp_manager:
  exp_dir: null
  name: "Conformer-CTC-Char"
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: "val_wer"
    mode: "min"
    save_top_k: 5
    always_save_nemo: True

  resume_if_exists: false
  resume_ignore_no_checkpoint: false

  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
