(begin
	(voice_kal_diphone)
	(set! utt1 (Utterance Text "Hello there"))
	(utt.synth utt1)
	(utt.save.wave utt1 "utt1.wav" nil)
	(voice_us1_mbrola)
	(set! utt2 (Utterance Text "Hello there"))
	(utt.synth utt2)
	(utt.save.wave utt2 "utt2.wav" nil)
	(voice_don_diphone)
	(set! utt3 (Utterance Text "Hello there"))
	(utt.synth utt3)
	(utt.save.wave utt3 "utt3.wav" nil)
	(voice_cmu_us_slt_arctic_hts)
	(set! utt4 (Utterance Text "Hello there"))
	(utt.synth utt4)
	(utt.save.wave utt4 "utt4.wav" nil)
)

